output.com.raytheon.uf.viz.npp.viirs.jar = bin/
bin.includes = META-INF/,\
               plugin.xml,\
<<<<<<< HEAD
=======
               localization/,\
>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
               res/,\
               com.raytheon.uf.viz.npp.viirs.jar
source.com.raytheon.uf.viz.npp.viirs.jar = src/
