output.com.raytheon.uf.viz.npp.nucaps.jar = bin/
bin.includes = META-INF/,\
<<<<<<< HEAD
=======
               localization/,\
>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
               plugin.xml,\
               com.raytheon.uf.viz.npp.nucaps.jar
source.com.raytheon.uf.viz.npp.nucaps.jar = src/
