#
# This file defines the levels used by the Vertical Interaction capability
#
# This is an incremental override file, indicating that the files at different
# localization levels will be combined.
# 
# Leaving the value empty after the = will remove a value from a lower Localization Level
# Example:
# remove interaction for FHAG levels
# FHAG=

# Syntax:
# masterLevel=level1,level2,level3
# values must be in units defined in the level_master Postgres table
FH=457.2,914.4,1524,3048,4572,6096,7620,9144,10668,12192
FHAG=457.2,914.4,1524,3048,4572,6096,7620,9144,10668,12192
