edex.root.directory=/awips2/ignite
architecture=x86_64

includegen.filter=raytheon

# AWIPSII core repositories required for build
<<<<<<< HEAD
core.repo=ufcore
core-foss.repo=ufcore-foss
=======
core.repo=AWIPS2_Core
core-foss.repo=AWIPS2_Core_FOSS
>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11

core.repositories=${core.repo},${core-foss.repo}
optional.repositories=

# Note: currently, there is a limit of 99 plugin directories.
<<<<<<< HEAD
# directories from ufcore-foss
dir.01=lib
# directories from ufcore
=======
# directories from AWIPS2_Core_FOSS
dir.01=lib
# directories from AWIPS2_Core
>>>>>>> 3a1a5c9814b49f276bea4ebd9e584974d6ea7a11
dir.02=common
dir.03=foss
dir.04=ignite
